### ISSUE TITLE
Link rust implementation

### ISSUE THREAD

**Issue by gammelalf** [myOmikron/rcp#2]
Please link my rust implemention in the README.md:
https://github.com/gammelalf/rcp-rs

**Comment by myOmikron** [comment]
- [ ] Use tags / releases based on [semantic versioning](https://semver.org)
- [ ] Publish the package on [crates.io](https://crates.io)

After these changes are done, I'll link the implementation

**Comment by gammelalf** [comment]
Done
- [v1.0.0](https://github.com/gammelalf/rcp-rs/tree/v1.0.0)
- [crates.io](https://crates.io/crates/rc_protocol)
